export const users = [
  {
    codigo: 1,
    nombre: 'Braulio',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
  {
    codigo: 1,
    nombre: 'Maria',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
  {
    codigo: 1,
    nombre: 'Andres',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
  {
    codigo: 1,
    nombre: 'Jose',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
  {
    codigo: 1,
    nombre: 'Pedro',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
  {
    codigo: 1111,
    nombre: 'Pedro',
    apellido: 'Pacheco',
    correo: 'user@gmail.com',
    sueldobruto: 2500,
    sueldoneto: 2150,
    dataempleado: 'url',
  },
];
